---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtools-ip-location
spec:
  selector:
    matchLabels:
      app: webtools-ip-location
  replicas: 1
  template:
    metadata:
      labels:
        app: webtools-ip-location
    spec:
      containers:
      - name: webtools-ip-location
        image: "ikoyski/webtools-ip-location:latest"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8092
---
apiVersion: v1
kind: Service
metadata:
  name: webtools-ip-location
spec:
  selector:
    app: webtools-ip-location
  ports:
  - protocol: "TCP"
    port: 8092
    targetPort: 8092
  type: NodePort
  